version: '3.4'

services:
  projectdn:
    image: ${DOCKER_REGISTRY}projectdn
    build:
      context: .
      dockerfile: ProjectDN/Dockerfile

  projectdnmain:
    image: ${DOCKER_REGISTRY}projectdnmain
    build:
      context: .
      dockerfile: ProjectDNMain/Dockerfile

